# Keep all in alphabetical order
components:
  instrumentation/active_storage/:
    - ymtdzzz

  instrumentation/aws_sdk/:
    - alextwoods
    - jterapin
    - NathanielRN

  instrumentation/grape/:
    - muripic

  instrumentation/graphql/:
    - rmoslogo
    - swalkinshaw

  instrumentation/grpc/:
    - michal-kazmierczak

  instrumentation/httpx/:
    - HoneyryderChuck

  instrumentation/mongo/:
    - johnnyshields

  instrumentation/racecar/:
    - chrisholmes

  instrumentation/rspec/:
    - chrisholmes

  instrumentation/que/:
    - indrekj

  processor/baggage/:
    - mikegoldsmith
    - robbkidd

  resources/container/:
    - scbjans

  sampler/xray/:
    - jj22ee

ignored-authors:
  - dependabot
