name: Component Owners
on:
  pull_request_target:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  run_self:
    runs-on: ubuntu-latest
    name: Auto Assign Owners
    steps:
      - uses: dyladan/component-owners@main
        with:
          config-file: .github/component_owners.yml
          repo-token: ${{ github.token }}
